### ISSUE TITLE
added +7 new dinos to the "allowed taming" list! (+4 removed)

### ISSUE THREAD

**Issue by xcoder86** [xcoder86/ARK-LEGENDS#3]
**the following dinos got added (+Saddles):**
> Moschops,
> Achatinas,
> Beelzebufos,
> Kairukus,
> Megaloceros,
> Procoptodons,
> Oviraptors

**we are thinking to add the following ones in the future:**
> Raptors,
> Sabertooth,
> Direwolfes,
> Carbonemys,
> Gigantopithecus,
> Lystrosaurus,
> Doedicturus,
> Ankylosaurus

**we removed 4 dinos from theisland map (disturbing ones):**
> Titanosaurs (to OP),
> Therizinos (to OP),
> Ichthyornis (Stealer),
> Leedsichthys (Raft Killer)

please comment below if you have any suggestions!

**Comment by JackTheRipper-99** [comment]
cool, i like it!
